cache: kafka
exchanges:
  BINANCE:
    l2_book:
      symbols: &id001
      - BTC-USDT
      - ETH-USDT
      - BNB-USDT
      - BCC-USDT
      - NEO-USDT
      - LTC-USDT
      - QTUM-USDT
      - ADA-USDT
      - XRP-USDT
      - EOS-USDT
      - TUSD-USDT
      - IOTA-USDT
      - XLM-USDT
      - ONT-USDT
      - TRX-USDT
      - ETC-USDT
      - ICX-USDT
      - VEN-USDT
      - NULS-USDT
      - VET-USDT
      - PAX-USDT
      - BCHSV-USDT
      - USDC-USDT
      - LINK-USDT
      - WAVES-USDT
      - BTT-USDT
      - USDS-USDT
      - ONG-USDT
      - HOT-USDT
      - ZIL-USDT
      - ZRX-USDT
      - FET-USDT
      - BAT-USDT
      - XMR-USDT
      - ZEC-USDT
      - IOST-USDT
      - CELR-USDT
      - DASH-USDT
      - NANO-USDT
      - OMG-USDT
      - THETA-USDT
      - ENJ-USDT
      - MITH-USDT
      - MATIC-USDT
      - ATOM-USDT
      - TFUEL-USDT
      - ONE-USDT
      - FTM-USDT
      - ALGO-USDT
      - USDSB-USDT
    retries: -1
    ticker: *id001
    trades: *id001
kafka:
  ip: 127.0.0.1
  port: 9092
  start_flush: true
parquet:
  append_counter: 4
  compression:
    codec: BROTLI
    level: 6
  del_file: true
  file_format:
  - exchange
  - symbol
  - data_type
  - timestamp
  path: /Users/anov/IdeaProjects/svoe/parquet
  prefix_date: true
storage:
- parquet
storage_interval: 60
storage_retries: 5
storage_retry_wait: 30
