cache: kafka
exchanges:
  BINANCE:
    l2_book:
      symbols: &id001
      - BTC-USDT
      - ETH-USDT
      - BNB-USDT
      - BCC-USDT
      - NEO-USDT
      - LTC-USDT
      - QTUM-USDT
      - ADA-USDT
      - XRP-USDT
      - EOS-USDT
      - TUSD-USDT
      - IOTA-USDT
      - XLM-USDT
      - ONT-USDT
      - TRX-USDT
      - ETC-USDT
      - ICX-USDT
      - VEN-USDT
      - NULS-USDT
      - VET-USDT
      - PAX-USDT
      - BCHSV-USDT
      - USDC-USDT
      - LINK-USDT
      - WAVES-USDT
      - BTT-USDT
      - USDS-USDT
      - ONG-USDT
      - HOT-USDT
      - ZIL-USDT
      - ZRX-USDT
      - FET-USDT
      - BAT-USDT
      - XMR-USDT
      - ZEC-USDT
      - IOST-USDT
      - CELR-USDT
      - DASH-USDT
      - NANO-USDT
      - OMG-USDT
      - THETA-USDT
      - ENJ-USDT
      - MITH-USDT
      - MATIC-USDT
      - ATOM-USDT
      - TFUEL-USDT
      - ONE-USDT
      - FTM-USDT
      - ALGO-USDT
      - USDSB-USDT
      - GTO-USDT
      - ERD-USDT
      - DOGE-USDT
      - DUSK-USDT
      - ANKR-USDT
      - WIN-USDT
      - COS-USDT
      - NPXS-USDT
      - COCOS-USDT
      - MTL-USDT
      - TOMO-USDT
      - PERL-USDT
      - DENT-USDT
      - MFT-USDT
      - KEY-USDT
      - STORM-USDT
      - DOCK-USDT
      - WAN-USDT
      - FUN-USDT
      - CVC-USDT
      - CHZ-USDT
      - BAND-USDT
      - BUSD-USDT
      - BEAM-USDT
      - XTZ-USDT
      - REN-USDT
      - RVN-USDT
      - HC-USDT
      - HBAR-USDT
      - NKN-USDT
      - STX-USDT
      - KAVA-USDT
      - ARPA-USDT
      - IOTX-USDT
      - RLC-USDT
      - MCO-USDT
      - CTXC-USDT
      - BCH-USDT
      - TROY-USDT
      - VITE-USDT
      - FTT-USDT
      - EUR-USDT
      - OGN-USDT
      - DREP-USDT
      - BULL-USDT
      - BEAR-USDT
      - ETHBULL-USDT
      - ETHBEAR-USDT
      - TCT-USDT
      - WRX-USDT
      - BTS-USDT
      - LSK-USDT
      - BNT-USDT
      - LTO-USDT
      - EOSBULL-USDT
      - EOSBEAR-USDT
      - XRPBULL-USDT
      - XRPBEAR-USDT
      - STRAT-USDT
      - AION-USDT
      - MBL-USDT
      - COTI-USDT
      - BNBBULL-USDT
      - BNBBEAR-USDT
      - STPT-USDT
      - WTC-USDT
      - DATA-USDT
      - XZC-USDT
      - SOL-USDT
      - CTSI-USDT
      - HIVE-USDT
      - CHR-USDT
      - BTCUP-USDT
      - BTCDOWN-USDT
      - GXS-USDT
      - ARDR-USDT
      - LEND-USDT
      - MDT-USDT
      - STMX-USDT
      - KNC-USDT
      - REP-USDT
      - LRC-USDT
      - PNT-USDT
      - COMP-USDT
      - BKRW-USDT
      - SC-USDT
      - ZEN-USDT
      - SNX-USDT
      - ETHUP-USDT
      - ETHDOWN-USDT
      - ADAUP-USDT
      - ADADOWN-USDT
      - LINKUP-USDT
      - LINKDOWN-USDT
      - VTHO-USDT
      - DGB-USDT
      - GBP-USDT
      - SXP-USDT
      - MKR-USDT
      - DAI-USDT
      - DCR-USDT
      - STORJ-USDT
      - BNBUP-USDT
      - BNBDOWN-USDT
      - XTZUP-USDT
      - XTZDOWN-USDT
      - MANA-USDT
      - AUD-USDT
      - YFI-USDT
      - BAL-USDT
      - BLZ-USDT
      - IRIS-USDT
      - KMD-USDT
      - JST-USDT
      - SRM-USDT
      - ANT-USDT
      - CRV-USDT
      - SAND-USDT
      - OCEAN-USDT
      - NMR-USDT
      - DOT-USDT
      - LUNA-USDT
      - RSR-USDT
      - PAXG-USDT
      - WNXM-USDT
      - TRB-USDT
      - BZRX-USDT
      - SUSHI-USDT
      - YFII-USDT
      - KSM-USDT
      - EGLD-USDT
      - DIA-USDT
      - RUNE-USDT
      - FIO-USDT
      - UMA-USDT
      - EOSUP-USDT
      - EOSDOWN-USDT
      - TRXUP-USDT
      - TRXDOWN-USDT
      - XRPUP-USDT
      - XRPDOWN-USDT
      - DOTUP-USDT
      - DOTDOWN-USDT
      - BEL-USDT
      - WING-USDT
      - LTCUP-USDT
      - LTCDOWN-USDT
      - UNI-USDT
      - NBS-USDT
      - OXT-USDT
      - SUN-USDT
      - AVAX-USDT
      - HNT-USDT
      - FLM-USDT
      - UNIUP-USDT
      - UNIDOWN-USDT
      - ORN-USDT
      - UTK-USDT
      - XVS-USDT
      - ALPHA-USDT
      - AAVE-USDT
      - NEAR-USDT
      - SXPUP-USDT
      - SXPDOWN-USDT
      - FIL-USDT
      - FILUP-USDT
      - FILDOWN-USDT
      - YFIUP-USDT
      - YFIDOWN-USDT
      - INJ-USDT
      - AUDIO-USDT
      - CTK-USDT
      - BCHUP-USDT
      - BCHDOWN-USDT
      - AKRO-USDT
      - AXS-USDT
      - HARD-USDT
      - DNT-USDT
      - STRAX-USDT
      - UNFI-USDT
      - ROSE-USDT
      - AVA-USDT
      - XEM-USDT
      - AAVEUP-USDT
      - AAVEDOWN-USDT
      - SKL-USDT
      - SUSD-USDT
      - SUSHIUP-USDT
      - SUSHIDOWN-USDT
      - XLMUP-USDT
      - XLMDOWN-USDT
      - GRT-USDT
      - JUV-USDT
      - PSG-USDT
      - 1INCH-USDT
      - REEF-USDT
      - OG-USDT
      - ATM-USDT
      - ASR-USDT
      - CELO-USDT
      - RIF-USDT
      - BTCST-USDT
      - TRU-USDT
      - CKB-USDT
      - TWT-USDT
      - FIRO-USDT
      - LIT-USDT
      - SFP-USDT
    retries: -1
    ticker: *id001
    trades: *id001
  COINBASE:
    l2_book:
      symbols: &id002
      - EOS-USD
      - ZEC-USD
      - OMG-USD
      - OXT-USD
      - ATOM-USD
      - LINK-USD
      - CGLD-USD
      - BAND-USD
      - YFI-USD
      - LRC-USD
      - ALGO-USD
      - UMA-USD
      - XTZ-USD
      - SNX-USD
      - COMP-USD
      - UNI-USD
      - BNT-USD
      - ZRX-USD
      - GRT-USD
      - FIL-USD
      - ETH-USD
      - NU-USD
      - BCH-USD
      - REP-USD
      - MKR-USD
      - DASH-USD
      - KNC-USD
      - DAI-USD
      - WBTC-USD
      - BAL-USD
      - LTC-USD
      - XLM-USD
      - REN-USD
      - NMR-USD
      - BTC-USD
      - AAVE-USD
      - ETC-USD
    retries: -1
    ticker: *id002
    trades: *id002
kafka:
  ip: 127.0.0.1
  port: 9092
  start_flush: true
parquet:
  S3:
    bucket: svoe.test.1
    key_id: AKIAJXSXXFCA3HN3T7GQ
    prefix: parquet
    secret: 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
  append_counter: 0
  compression:
    codec: BROTLI
    level: 6
  del_file: true
  file_format:
  - exchange
  - symbol
  - data_type
  - timestamp
  prefix_date: true
storage:
- parquet
storage_interval: 60
storage_retries: 5
storage_retry_wait: 30
