cache: kafka
exchanges:
  KRAKEN:
    l2_book:
      max_depth: 1000
      symbols: &id001
      - AAVE-USD
      - ADA-USD
      - ALGO-USD
      - ANT-USD
      - ATOM-USD
      - AUD-USD
      - BAL-USD
      - BAT-USD
      - BCH-USD
      - COMP-USD
      - CRV-USD
      - DAI-USD
      - DASH-USD
      - DOT-USD
      - EOS-USD
      - FIL-USD
      - FLOW-USD
      - GNO-USD
      - GRT-USD
      - ICX-USD
      - KAVA-USD
      - KEEP-USD
      - KNC-USD
      - KSM-USD
      - LINK-USD
      - LSK-USD
      - MANA-USD
      - NANO-USD
      - OMG-USD
      - OXT-USD
      - PAXG-USD
      - QTUM-USD
      - REPV2-USD
      - SC-USD
      - SNX-USD
      - STORJ-USD
      - TBTC-USD
      - TRX-USD
      - UNI-USD
      - USDC-USD
      - USDT-USD
      - WAVES-USD
      - DOG-USD
      - ETC-USD
      - ETH-USD
      - LTC-USD
      - MLN-USD
      - REP-USD
      - XTZ-USD
      - BTC-USD
      - XLM-USD
      - XMR-USD
      - XRP-USD
      - ZEC-USD
      - YFI-USD
      - EUR-USD
      - GBP-USD
    retries: -1
    ticker: *id001
    trades: *id001
kafka:
  ip: 127.0.0.1
  port: 9092
  start_flush: true
parquet:
  S3:
    bucket: svoe.test.1
    key_id: AKIAJXSXXFCA3HN3T7GQ
    prefix: parquet
    secret: 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
  append_counter: 0
  compression:
    codec: BROTLI
    level: 6
  del_file: true
  file_format:
  - exchange
  - symbol
  - data_type
  - timestamp
  prefix_date: true
storage:
- parquet
storage_interval: 120
storage_retries: 5
storage_retry_wait: 30
