cache: kafka
exchanges:
  COINBASE:
    l2_book:
      symbols: &id001
      - CGLD-USD
      - LTC-USD
      - REN-USD
      - COMP-USD
      - MKR-USD
      - ETC-USD
      - LINK-USD
      - OXT-USD
      - BAND-USD
      - GRT-USD
      - BNT-USD
      - XLM-USD
      - SNX-USD
      - XTZ-USD
      - ALGO-USD
      - ETH-USD
      - ZEC-USD
      - KNC-USD
      - ZRX-USD
      - UMA-USD
      - NU-USD
      - AAVE-USD
      - BCH-USD
      - DAI-USD
      - EOS-USD
      - BAL-USD
      - OMG-USD
      - LRC-USD
      - FIL-USD
      - DASH-USD
      - WBTC-USD
      - NMR-USD
      - YFI-USD
      - ATOM-USD
      - UNI-USD
      - BTC-USD
      - REP-USD
    retries: -1
    ticker: *id001
    trades: *id001
kafka:
  ip: 127.0.0.1
  port: 9092
  start_flush: true
parquet:
  S3:
    bucket: svoe.test.1
    key_id: AKIAJXSXXFCA3HN3T7GQ
    prefix: parquet
    secret: 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
  append_counter: 0
  compression:
    codec: BROTLI
    level: 6
  del_file: true
  file_format:
  - exchange
  - symbol
  - data_type
  - timestamp
  prefix_date: true
storage:
- parquet
storage_interval: 60
storage_retries: 5
storage_retry_wait: 30
