cache: kafka
exchanges:
  BINANCE:
    l2_book:
      symbols: &id001
      - ETH-BTC
      - LTC-BTC
      - BNB-BTC
      - NEO-BTC
      - QTUM-ETH
      - EOS-ETH
      - SNT-ETH
      - BNT-ETH
      - BCC-BTC
      - GAS-BTC
    retries: -1
    ticker: *id001
    trades: *id001
kafka:
  ip: 127.0.0.1
  port: 9092
  start_flush: true
parquet:
  append_counter: 4
  compression:
    codec: BROTLI
    level: 6
  del_file: true
  file_format:
  - exchange
  - symbol
  - data_type
  - timestamp
  path: /Users/anov/IdeaProjects/svoe/parquet
  prefix_date: true
storage:
- parquet
storage_interval: 60
storage_retries: 5
storage_retry_wait: 30
