cache: kafka
exchanges:
  BINANCE:
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: &id001
      - BTC-USDT
      - ETH-USDT
      - BNB-USDT
      - NEO-USDT
      - LTC-USDT
      - QTUM-USDT
      - ADA-USDT
      - XRP-USDT
      - EOS-USDT
      - TUSD-USDT
    retries: -1
    ticker: *id001
    trades: *id001
  COINBASE:
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: &id002
      - ETH-USD
      - MATIC-USD
      - NU-USD
      - CRV-USD
      - EOS-USD
      - SUSHI-USD
      - DASH-USD
      - FIL-USD
      - SKL-USD
      - ETC-USD
    retries: -1
    ticker: *id002
    trades: *id002
  HUOBI:
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: &id003
      - APN-USDT
      - MASS-USDT
      - BADGER-USDT
      - FILDA-USDT
      - VALUE-USDT
      - DF-USDT
      - ABT-USDT
      - HPT-USDT
      - FRONT-USDT
      - POND-USDT
    retries: -1
    trades: *id003
  KRAKEN:
    l2_book:
      book_delta: true
      max_depth: 100
      symbols: &id004
      - AAVE-USD
      - ADA-USD
      - ALGO-USD
      - ANT-USD
      - ATOM-USD
      - AUD-USD
      - BAL-USD
      - BAT-USD
      - BCH-USD
      - COMP-USD
    retries: -1
    ticker: *id004
    trades: *id004
kafka:
  ip: 127.0.0.1
  port: 9092
  start_flush: true
parquet:
  S3:
    bucket: svoe.test.1
    key_id: AKIAJXSXXFCA3HN3T7GQ
    prefix: parquet
    secret: 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
  append_counter: 0
  compression:
    codec: BROTLI
    level: 6
  del_file: true
  file_format:
  - exchange
  - symbol
  - data_type
  - timestamp
  prefix_date: true
storage:
- parquet
storage_interval: 90
storage_retries: 5
storage_retry_wait: 30
